name: Build Electron App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        # os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        cache: 'npm'
        cache-dependency-path: './package-lock.json'

    - name: Install dependencies
      run: npm ci
      
    - name: Build TypeScript
      run: npm run build
      
    - name: Build Electron app
      run: npm run dist

    # - name: Upload Windows artifacts
    #   if: matrix.os == 'windows-latest'
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: windows-build
    #     path: build/*.exe
        
    # - name: Upload macOS artifacts
    #   if: matrix.os == 'macos-latest'
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: macos-build
    #     path: build/*.dmg
        
    - name: Upload Linux artifacts
      if: matrix.os == 'ubuntu-latest'
      uses: actions/upload-artifact@v4
      with:
        name: linux-build
        path: |
          build/*.AppImage
          build/*.deb
